name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install TA-Lib C library
        run: |
          sudo apt-get update
          sudo apt-get install -y libta-lib0 libta-lib-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Ensure Python TA-Lib wrapper is installed
          pip install TA-Lib
          # Install core Python packages including pytest for tests
          pip install pytest pandas python-json-logger
          # If using conda environment file, install other deps too
          if [ -f environment.yml ]; then
            pip install -r <(grep -E "^- [a-zA-Z0-9]" environment.yml | sed 's/^- //')
          fi

      - name: Run lint
        run: |
          pip install black flake8
          black .
          # Visa version och sökväg till loaded config
          flake8 --version
          # Kör lint med er config-fil
          flake8 . --config .flake8

      - name: Run tests
        run: |
          python -m pytest --maxfail=1 --disable-warnings -q

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: dockerfile
          push: false
          tags: tradingbot:latest
