name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_SECRET }}
      EXCHANGE_NAME: ${{ secrets.EXCHANGE_NAME }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniconda & create env
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          environment-file: environment.yml
          activate-environment: tradingbot_env
          auto-activate-base: false
          use-mamba: true

      - name: Update pip inside conda env
        run: |
          conda run -n tradingbot_env python -m pip install --upgrade pip

      - name: Run lint
        run: |
          conda run -n tradingbot_env black .
          conda run -n tradingbot_env flake8 --version
          conda run -n tradingbot_env flake8 . --config .flake8

      - name: Run tests
        run: |
          conda run -n tradingbot_env pytest --maxfail=1 --disable-warnings -q

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: dockerfile
          push: false
          tags: tradingbot:latest
